apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbb-scheduler-debian8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbb-scheduler
      instance: debian8
  template:
    metadata:
      labels:
        app: bbb-scheduler
        instance: debian8
    spec:
      containers:
      - image: ...
        name: bbb-scheduler
        ports:
        - containerPort: 8981
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
