apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: bbb-frontend
spec:
  ports:
  - port: 8980
    protocol: TCP
  selector:
    app: bbb-frontend
  type: LoadBalancer
