apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbb-browser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bbb-browser
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bbb-browser
    spec:
      containers:
      - image: ...
        name: bbb-browser
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          defaultMode: 400
          name: bbb-config
        name: config
