apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: bbb-scheduler-debian9
spec:
  ports:
  - port: 8981
    protocol: TCP
  selector:
    app: bbb-scheduler
    instance: debian9
  type: ClusterIP
