apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbb-worker-debian8
spec:
  replicas: 8
  selector:
    matchLabels:
      app: bbb-worker
      instance: debian8
  template:
    metadata:
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
      labels:
        app: bbb-worker
        instance: debian8
    spec:
      containers:
      - args:
        - -browser-url=http://bbb-browser/
        - -scheduler=bbb-scheduler-debian8:8981
        image: ...
        name: bbb-worker
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          defaultMode: 400
          name: bbb-config
        name: config
