apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bbb-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bbb-frontend
  template:
    metadata:
      labels:
        app: bbb-frontend
    spec:
      containers:
      - args:
        - -scheduler=debian9|bbb-scheduler-debian9:8981
        image: ...
        name: bbb-frontend
        ports:
        - containerPort: 8980
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          defaultMode: 400
          name: bbb-config
        name: config
