version: '3'
services:
  bbb-frontend:
    image: bazel/cmd/bbb_frontend:bbb_frontend_container
    command:
    - -scheduler=debian8|bbb-scheduler-debian8:8981
    - -scheduler=ubuntu16-04|bbb-scheduler-ubuntu16-04:8981
    ports:
    - 7980:80
    - 8980:8980
    volumes:
    - ./config-browser-frontend-worker:/config

  bbb-storage-0:
    image: bazel/cmd/bbb_storage:bbb_storage_container
    expose:
    - 8982
    ports:
    - 7982:80
    volumes:
    - ./config-storage:/config
    - ./storage-ac-0:/storage-ac
    - ./storage-cas-0:/storage-cas
  bbb-storage-1:
    image: bazel/cmd/bbb_storage:bbb_storage_container
    expose:
    - 8982
    ports:
    - 17982:80
    volumes:
    - ./config-storage:/config
    - ./storage-ac-1:/storage-ac
    - ./storage-cas-1:/storage-cas

  bbb-browser:
    image: bazel/cmd/bbb_browser:bbb_browser_container
    ports:
    - 7983:80
    volumes:
    - ./config-browser-frontend-worker:/config

  bbb-scheduler-debian8:
    image: bazel/cmd/bbb_scheduler:bbb_scheduler_container
    expose:
    - 8981
    ports:
    - 7981:80
  bbb-worker-debian8:
    image: bazel/cmd/bbb_worker:bbb_worker_container
    command:
    - -browser-url=http://localhost:7983/
    - -concurrency=4
    - -scheduler=bbb-scheduler-debian8:8981
    ports:
    - 7984:80
    volumes:
    - ./config-browser-frontend-worker:/config
    - ./worker-debian8:/worker
  bbb-runner-debian8:
    image: bazel/cmd/bbb_runner:bbb_runner_debian8_container
    network_mode: none
    volumes:
    - ./worker-debian8:/worker

  bbb-scheduler-ubuntu16-04:
    image: bazel/cmd/bbb_scheduler:bbb_scheduler_container
    expose:
    - 8981
    ports:
    - 17981:80
  bbb-worker-ubuntu16-04:
    image: bazel/cmd/bbb_worker:bbb_worker_container
    command:
    - -browser-url=http://localhost:7983/
    - -concurrency=4
    - -scheduler=bbb-scheduler-ubuntu16-04:8981
    ports:
    - 17984:80
    volumes:
    - ./config-browser-frontend-worker:/config
    - ./worker-ubuntu16-04:/worker
  bbb-runner-ubuntu16-04:
    image: bazel/cmd/bbb_runner:bbb_runner_ubuntu16_04_container
    network_mode: none
    volumes:
    - ./worker-ubuntu16-04:/worker
